# Generated by Django 5.0.6 on 2024-06-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_scope_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['is_main'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
